# Generated by Django 4.2.9 on 2024-01-25 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, max_length=20)),
                ('password', models.CharField(default=None, max_length=255)),
            ],
        ),
    ]
